feature: added context-path support
zeebe-io/zeebe-simple-monitor pull request #209
Opened 2020-12-19 01:09 UTC by xamien

I follow up on pull request for route prefix https://github.com/zeebe-io/zeebe-simple-monitor/pull/171/ using
`server.servlet.context-path`

@shawnsarwar

2020-12-19 01:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zeebe-io/zeebe-simple-monitor?pullRequest=209) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zeebe-io/zeebe-simple-monitor?pullRequest=209) before we can accept your contribution.<br/><hr/>**Michal Kotek** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zeebe-io/zeebe-simple-monitor?pullRequest=209) it.</sub>

2021-01-04 09:54 UTC, saig0 requested changes
@xamien thank you for your contribution :tada: 

It looks good :+1: I just added some minor suggestions.
Please have a look. 

And please have a look at the CLA bot. Maybe, the email of the commit is different from GitHub. See:

> Michal Kotek seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

2021-01-04 09:54 UTC, saig0 commented on src/main/resources/public/js/app.js
> +                stompClient.send(base_path + "notifications", {},
Following DRY ("dont-repeat-yourself"), we could extract the building of the path into a method.

2021-01-04 09:54 UTC, saig0 commented on src/main/java/io/zeebe/monitor/rest/ViewController.java
> +    model.put("context-path", base_path);
Following DRY, we can extract this part into a method.

2021-01-16 22:29 UTC, xamien commented
@saig0 thank you for review. I hope that I worked all comments.

2021-01-19 05:27 UTC, saig0 approved these changes
Looks good :tada: 

I'll add some minor changes myself to clean up.

2021-01-19 05:35 UTC, merged